DROP TABLE CALENDAR;
DROP SEQUENCE CALENDARSEQ;

CREATE SEQUENCE CALENDARSEQ;

CREATE TABLE CALENDAR(
	CALENDAR_ID NUMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(100) NOT NULL,
	STUDY_GROUP_ID NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);



INSERT INTO CALENDAR
VALUES(CALENDARSEQ.NEXTVAL, 'test 계정', 1, 'TEST', '2021-06-15', '2021-06-17', 'TEST TEST', SYSDATE);


SELECT * FROM CALENDAR;

SELECT CALENDAR_ID, MEMBER_ID, STUDY_GROUP_ID, TITLE, START_DATE, END_DATE, CONTENT, REGDATE
FROM CALENDAR
ORDER BY CALENDAR_ID DESC;