SELECT *
FROM MEMBER;

SELECT *
FROM STUDY_GROUP_MEMBER;

SELECT A.MEMBER_NICKNAME, A.MEMBER_LOC, A.MEMBER_PHONENUMBER, B.ROLE
FROM MEMBER A
FULL OUTER JOIN STUDY_GROUP_MEMBER B
ON A.MEMBER_EMAIL = B.MEMBER_EMAIL
WHERE STUDY_GROUP_ID = 144;